### ISSUE TITLE
improve markdown editor

### ISSUE THREAD

**Issue by tmfrnz** [marine-defrag/marine-defrag-client#130]
basically same as
https://github.com/dumparkltd/advocacy-tracker-client/issues/20

**Comment by vbojilova** [comment]
- [ ] functionality for preview 
- [ ] markdown field

**Comment by tmfrnz** [comment]
![image](https://github.com/dumparkltd/marine-defrag-client/assets/5811956/64197280-0f2a-4272-9be0-2e4a2279a694)
