### ISSUE TITLE
mobile: overlapping buttons in map view 

### ISSUE THREAD

**Issue by vbojilova** [marine-defrag/marine-defrag-client#160]
<img width="307" alt="Screen Shot 2024-05-31 at 6 45 04 PM" src="https://github.com/marine-defrag/marine-defrag-client/assets/37880309/637cc334-ccc9-4089-a329-094ac2f0c5c5">

map/list button pill overlap map zoom functionality in mobile

**Comment by tmfrnz** [comment]
thanks @vbojilova, although I think the zoom buttons should be hidden on mobile 
https://github.com/marine-defrag/marine-defrag-client/blob/production/app/containers/MapControl/MapWrapperLeaflet.js#L155
(however maybe this could/should be moved to `let leafletOptions` above)
